Constant
traitecoevo/rmot pull request #10
Opened 2024-04-03 05:53 UTC by Tess-LaCoil

Constant model is ready to be folded into the main branch, passes all tests.

2024-04-03 06:12 UTC, fontikar commented on tests/testthat/helper-testing.R
Will `rmot_test_single_individual `and `rmot_test_multi_individual` be used for other models other than the constant?

2024-04-03 06:12 UTC, fontikar commented on inst/stan/constant_single_ind.stan
I think best if @dfalster also reviews PR and quickly looks over the .stan files. This is out of my expertise

2024-04-03 06:13 UTC, fontikar commented on inst/stan/constant_multi_ind.stan
@dfalster would you mind having a quick check of these .stan files please? :)

2024-04-03 06:14 UTC, fontikar commented on .github/workflows/R-CMD-check.yaml
@Tess-LaCoil would you mind removing `, constant` from line 5 below? I added it there to trigger the CI to automatically test the constant branch, but now that we are at a merging PR stage, this can be removed. We won't need that trigger once its on `master`

2024-04-03 06:15 UTC, fontikar reviewed
Nice work! Just a few comments that need address and awaiting for @dfalster's eyes on Stan related files. Once all address we can merge away! 🌳

2024-04-03 21:43 UTC, dfalster requested changes
Well done team! A query about the way step is represented.

2024-04-03 23:27 UTC, Tess-LaCoil commented on tests/testthat/helper-testing.R
Yes, they form the basis of the testing template for the respective datasets.

2024-04-04 01:17 UTC, Tess-LaCoil commented
I've made the requested changes and pushed them to the constant branch.

2024-04-04 01:26 UTC, dfalster approved these changes
Nice, feel free to merge once tests have passed.

I suggest merging with a "squash commit", this will compress all the work non this branch into a single commit. Write a nice commit message than describes what has been added in this merge.

2024-04-04 01:33 UTC, fontikar approved these changes
Nice work Tess 🥳

2024-04-04 04:25 UTC, merged