Power model add
traitecoevo/rmot pull request #13
Opened 2024-04-09 11:35 UTC by Tess-LaCoil

Added the power law model.

2024-04-09 20:35 UTC, fontikar approved these changes
Looks great to me! Nice work so glad we have a workflow now! :D Have no viewed Stan files in much detail, @dfalster can we lean on you for that please? 🙏

2024-04-09 21:36 UTC, dfalster requested changes
Nice work Tess. Looks great. However, I suggest we write power law as  dx/dt = a (x/x_c)^b. Your  implementation has x_c=1. a general guide would be that x_c ~= mean(x), but rather than estimating from the data, it would be better to set this in the model setup as a specified quantify. Without this, the slope and intercept become heavily correlated and hard to converge.

2024-04-10 05:45 UTC, Tess-LaCoil commented
Changes to power law model done. @dfalster I don't know if the data generation process is sane as I produce y_bar values and pass them along with the other DE parameters to used to determine true sizes over time. Those true values also get passed to the model, but I assume in practice these would be estimated from the data or something.

2024-04-10 07:05 UTC, dfalster requested changes
Sorry , more changes!

2024-04-10 07:05 UTC, dfalster commented on inst/stan/power_multi_ind.stan
> +  real y_bar[n_ind];
Sorry if this wasn't clear. This should no vary by individuals, it's a single value applying to the whole dataset

2024-04-10 07:05 UTC, dfalster commented on inst/stan/power_multi_ind.stan
> +  real DE(real y, real y_bar, vector pars){
why not include y_bar in pars?

2024-04-10 08:25 UTC, Tess-LaCoil commented on inst/stan/power_multi_ind.stan
> +  real DE(real y, real y_bar, vector pars){
Can do.

2024-04-18 05:02 UTC, dfalster approved these changes

2024-04-19 01:07 UTC, merged