Update readme
traitecoevo/rmot pull request #16
Opened 2024-04-19 01:08 UTC by Tess-LaCoil

Updated the readme to include a blurb, description of the mathematical structure, and definition of the different implemented models.

2024-04-19 02:58 UTC, fontikar commented on README.Rmd
The math is not formatted correctly. 

You can preview your output but clicking "branch" and selecting update-readme on the GitHub repo website, or clicking "preview" in RStudio where it will render it for you in the Viewer pane

<img width="942" alt="Screenshot 2024-04-19 at 12 58 22 PM" src="https://github.com/traitecoevo/rmot/assets/12161802/13f067c2-eb37-42a5-aebb-4b90b1c5ec01">

2024-04-19 02:59 UTC, fontikar commented on README.Rmd
Solution might be in here: https://github.com/STAT545-UBC/Discussion/issues/102

2024-04-19 02:59 UTC, fontikar commented on README.md
As above for README.Rmd

2024-04-19 03:00 UTC, fontikar requested changes
Just need to fix those equations! :)

2024-04-19 03:08 UTC, fontikar commented on README.Rmd
Not sure I mentioned this in the past, you only need to edit the README.Rmd and click render and it will update the README.md. 

If problem persists, you can ditch the RMD and just use the .md 

- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
- https://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog/72310304#72310304

2024-04-19 03:40 UTC, Tess-LaCoil commented on README.Rmd
Ahh, I thought the RMD and MD would do the same thing with what github said about rendering maths. How do I ditch the RMD?

2024-04-19 10:24 UTC, Tess-LaCoil commented
Managed to work out all the markdown breaking LaTeX, renders properly now.

2024-04-19 10:25 UTC, Tess-LaCoil commented on README.Rmd
Done.

2024-04-19 12:31 UTC, fontikar commented on README.md
> +                         obs\_index = 1:10,                          #vector length n_obs
Nit sure why obs\_index has rendered Iike this? Just need a minor fix

2024-04-22 03:08 UTC, fontikar approved these changes
Nice work!

2024-04-22 03:33 UTC, merged